### ISSUE TITLE
致-作者

### ISSUE THREAD

**Issue by ysctest** [pengzhile/CopyWhoList#2]
您好前辈，我是从 https://zhile.io/ 从您发的 Jetbrains 而来。
我是一个新手菜鸟，最近在考虑搭建个人blog，但是我的前端写的很丑，我感觉您的blog 风格简约且舒适。您能不能将源码分享一下。如若可以请联系 ysctest@163.com 不胜感激

**Comment by pengzhile** [comment]
我的博客用的hexo 静态博客系统 + next 主题，你可以搜索关键字看一下。做出来效果是一样的。

**Comment by ysctest** [comment]
十分感谢
