### ISSUE TITLE
关于：DBeaver Enterprise 21.0 企业版激活方法

### ISSUE THREAD

**Issue by alterem** [pengzhile/CopyWhoList#6]
DBeaver Enterprise 21.0 企业版激活方法，没有放置最新的agent文件

**Comment by pengzhile** [comment]
老的就可以。

**Comment by bianguolong** [comment]
大佬，DBeaver Ultimate Edition 21.0已经放出，什么时候更新一下agent

**Comment by pengzhile** [comment]
> 大佬，DBeaver Ultimate Edition 21.0已经放出，什么时候更新一下agent

博客文章写了，烦请查阅。

**Comment by bianguolong** [comment]
EE没有问题，UE就不行了！

**Comment by fengzhao** [comment]
ee好像也有点问题呢

**Comment by alterem** [comment]
> > 大佬，DBeaver Ultimate Edition 21.0已经放出，什么时候更新一下agent
> 
> 博客文章写了，烦请查阅。

刚刚有尝试最新的 DBeaverUltimate 不能激活
